name: Publish specfit package

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build-n-publish:
    name: Build and publish specfit to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install pip
      run: python -m pip install --upgrade pip 
    - name: Install hatch
      run: pip install hatch
    - name: Build a binary wheel and a source tarball
      run: hatch build
    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
